"""Hardware boundary used by the SO101 console; other adapters can implement it."""
from typing import Protocol


class RobotDriver(Protocol):
    def connect(self) -> 'RobotDriver': ...
    def state(self, wait: float = 0) -> dict: ...
    def enable(self) -> dict: ...
    def move(self, joints_deg: list[float], gripper: float) -> dict: ...
    def hold(self) -> dict: ...
    def close(self) -> None: ...
